### ISSUE TITLE
Adds Context to go-server template

### ISSUE THREAD

**Issue by ryutah** [ryutah/openapi-generator#1]
## TODO

- fix templates

refs https://github.com/OpenAPITools/openapi-generator/issues/6657

**Comment by ryutah** [comment]
hmm...

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:37 min
[INFO] Finished at: 2020-08-14T07:38:26+00:00
[INFO] Final Memory: 57M/224M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (jacoco-site) on project openapi-generator: An error has occurred in JaCoCo report generation. Error while creating report: null: EOFException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (jacoco-site) on project openapi-generator: An error has occurred in JaCoCo report generation.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in JaCoCo report generation.
        at org.jacoco.maven.AbstractReportMojo.execute(AbstractReportMojo.java:168)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 27 more
Caused by: org.apache.maven.reporting.MavenReportException: Error while creating report: null
        at org.jacoco.maven.AbstractReportMojo.executeReport(AbstractReportMojo.java:184)
        at org.jacoco.maven.AbstractReportMojo.execute(AbstractReportMojo.java:166)
        ... 29 more
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
        at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
        at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
        at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
        at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
        at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
        at org.jacoco.maven.ReportSupport.loadExecutionData(ReportSupport.java:89)
        at org.jacoco.maven.ReportMojo.loadExecutionData(ReportMojo.java:61)
        at org.jacoco.maven.AbstractReportMojo.executeReport(AbstractReportMojo.java:178)
        ... 30 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openapi-generator
```

**Comment by ryutah** [comment]
done
